#!/bin/sh /etc/rc.common
# iup at boot
# Copyright (C) 2007 OpenWrt.org

START=98
STOP=15
USE_PROCD=1

start_service() {
        procd_open_instance bet_server
		procd_set_param command bet_server
		procd_set_param respawn
		procd_close_instance
}
